<%@ Page Title="Produkty" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Products.aspx.cs" Inherits="OrderDemoWebForms.Pages.Product.Products" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">

    <div>
        <h2><%: Title %></h2>

        <hr />
        <h3>Přidat produkt</h3>
        <table class="nav-justified">
            <tr>
                <td style="height: 25px">Kód produktu</td>
                <td style="height: 25px">
                    <asp:TextBox ID="txtCode" runat="server" />
                    <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="txtCode" ErrorMessage="RequiredFieldValidator" ForeColor="#FF3300">Je třeba zadat kód produktu</asp:RequiredFieldValidator>
                    <asp:CompareValidator ID="CompareValidator4" runat="server" ControlToValidate="txtCode" ErrorMessage="CompareValidator" ForeColor="#FF3300" Operator="DataTypeCheck" Type="Integer">Kód může obsahovat pouze čísla</asp:CompareValidator>
                </td>
            </tr>
            <tr>
                <td style="height: 25px">Název produktu</td>
                <td style="height: 25px">
                    <asp:TextBox ID="txtName" runat="server" />
                    <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ControlToValidate="txtName" ErrorMessage="RequiredFieldValidator" ForeColor="#FF3300">Je třeba zadat název produktu</asp:RequiredFieldValidator>
                </td>
            </tr>
            <tr>
                <td>Cena</td>
                <td>
                    <asp:TextBox ID="txtPrice" runat="server" />
                    <asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server" ControlToValidate="txtPrice" ErrorMessage="RequiredFieldValidator" ForeColor="#FF3300">Je třeba zadat cenu</asp:RequiredFieldValidator>
                    <asp:CompareValidator ID="CompareValidator5" runat="server" ControlToValidate="txtPrice" ErrorMessage="CompareValidator" ForeColor="#FF3300" Operator="DataTypeCheck" Type="Double">Cena může obsahovat pouze desetinné číslo</asp:CompareValidator>
                </td>
            </tr>
        </table>
        <br />
        <asp:Button ID="AddProducId" runat="server" OnClick="AddProduct_Click" Text="Přidat" />
        <br />
    </div>

    <div>
        <hr />
        <h3>Přehled produktů</h3>
        <asp:GridView ID="ProductsGrid" runat="server" AutoGenerateColumns="False" Width="458px" AutoGenerateDeleteButton="True"
            OnRowDeleting="ProductsGridView_RowDeleting"
            AutoGenerateEditButton="True"
            OnRowUpdating="ProductsGridView_RowUpdating"
            OnRowEditing="ProductsGridView_RowEditing">
            <Columns>
                <asp:TemplateField HeaderText="Id">
                    <ItemTemplate>
                        <asp:Label ID="Id" runat="server" Text='<%# Bind("Id") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Kód produktu">
                    <ItemTemplate>
                        <asp:Label ID="Code" runat="server" Text='<%# Bind("Code") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Název produktu">
                    <ItemTemplate>
                        <asp:Label ID="Name" runat="server" Text='<%# Bind("Name") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Cena">
                    <ItemTemplate>
                        <asp:Label ID="Price" runat="server" Text='<%# Bind("Price") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>

        </asp:GridView>

        <hr />
    </div>

</asp:Content>
